FROM mono:6.12.0.182

RUN apt update && apt upgrade -y && apt install wget unzip -y;
RUN wget wget https://github.com/dotnet/docfx/releases/download/v2.51/docfx.zip; \
    unzip docfx.zip -d /usr/local/lib/docfx; \
    chmod +x /usr/local/lib/docfx/docfx.exe; \
