FROM mcr.microsoft.com/dotnet/sdk:10.0-windowsservercore-ltsc2022

SHELL ["powershell", "-command"]

ARG DOCFX_VERSION=2.78.5

RUN dotnet tool install docfx --tool-path C:\tools\docfx --version $env:DOCFX_VERSION

ENV PATH="C:\tools\docfx;${PATH}"
