FROM mono:6.12.0.182

RUN apt update && apt upgrade -y && apt install wget unzip -y;
RUN wget wget https://github.com/dotnet/docfx/releases/download/2.65.1/docfx-win-x64-2.65.1.zip; \
    unzip docfx-win-x64-2.65.1.zip -d /usr/local/lib/docfx; \
    chmod +x /usr/local/lib/docfx/docfx; \
