name: Build Documentation Site

on:
  workflow_dispatch:
  schedule:
  - cron: '0 2 * * *'

permissions: read-all

env:
  DOCFX_VERSION: 2.78.5
  DOTNET_VERSION: 10.x

jobs:
  documentation:
    runs-on: ubuntu-latest
    permissions:
      contents: write      
    steps:
      - name: Wait for actions to finish
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout master branch
        uses: actions/checkout@v6
        with:
          ref: master
          path: master
      - name: Checkout dev branch
        uses: actions/checkout@v6
        with:
          ref: dev
          path: dev
      - name: Checkout gh-pages branch
        uses: actions/checkout@v6
        with:
          ref: gh-pages
          path: gh-pages
      - name: Setup .NET 10.0
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Install DocFX
        run: dotnet tool install -g docfx --version ${{ env.DOCFX_VERSION }}
      
      - name: Build docs
        shell: pwsh
        run: |
          ./dev/pages/Build-Site.ps1
      - name: Add & Commit & Push
        uses: EndBug/add-and-commit@v9
        with:
          cwd: ./gh-pages          
          push: true          
