name: Cleanup old nightly PowerShell Releases

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

permissions: read-all
    
jobs:
  # This workflow contains a single job called "cleanup"
  cleanup:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
      with: 
        ref: dev
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
    - name: Unlist nightly nuget packages
      env:
        POWERSHELLGALLERY_API_KEY : ${{ secrets.POWERSHELLGALLERY_API_KEY }}
      shell: pwsh
      run: |
        ./build/Unlist-Nightly.ps1
